import '@/styles/global.scss';
import { CartProvider } from '@/utils/context/useCart';
import { ModalProvider } from '@/utils/context/useModal';
import { Metadata } from 'next';
import { Red_Hat_Text } from 'next/font/google';

const redHatText = Red_Hat_Text({
  subsets: ['latin'],
  fallback: ['sans-serif'],
  weight: ['400', '600'],
  variable: '--font',
});

export const metadata: Metadata = {
  title: 'Product list',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ModalProvider>
      <CartProvider>
        <html lang="en">
          <body className={redHatText.variable}>
            <div id="modal" />
            {children}
          </body>
        </html>
      </CartProvider>
    </ModalProvider>
  );
}
